#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_npcmap.py - Gera modules/game_npcmap/npcs.lua a partir dos NPCs do servidor.

Lê o arquivo de spawns do mapa (forgotten-spawn.xml) + os XMLs de NPC
(data/npc/*.xml) do servidor e emite uma tabela Lua estatica com todos os
NPCs (nome, posicao de spawn absoluta e outfit).

Uso:
    python3 gen_npcmap.py

Ajuste os caminhos abaixo se o servidor/cliente estiverem em outro lugar.
Rode de novo sempre que o mapa/NPCs mudarem para regenerar npcs.lua.
"""

import os
import sys
import xml.etree.ElementTree as ET

SERVER = r"C:\Users\imfis\Desktop\Avatar-Compraado-server"
CLIENT = r"C:\Users\imfis\Desktop\Avatar-comprado-client"
SPAWN_FILE = os.path.join(SERVER, "data", "world", "forgotten-spawn.xml")
NPC_DIR = os.path.join(SERVER, "data", "npc")
OUT_FILE = os.path.join(CLIENT, "modules", "game_npcmap", "npcs.lua")


def main():
    tree = ET.parse(SPAWN_FILE)
    root = tree.getroot()

    npcs = []          # (z, x, y, name)
    missing_xml = {}   # name -> count (spawned but no npc xml = engine never spawns)

    for spawn in root.findall("spawn"):
        cx = int(spawn.get("centerx"))
        cy = int(spawn.get("centery"))
        cz = int(spawn.get("centerz"))
        for child in spawn:
            if child.tag != "npc":
                continue
            name = child.get("name")
            if not name:
                continue
            x = cx + int(child.get("x", 0) or 0)
            y = cy + int(child.get("y", 0) or 0)
            # IMPORTANTE: no spawn.cpp o z do <npc> e ATRIBUIDO (nao somado ao
            # centerz) - linha usa 'placePos.z /*+*/= intValue' (comentario no +).
            z = int(child.get("z") or 0) or cz
            # NPC xml (lowercased filename, same rule the engine uses)
            xml_path = os.path.join(NPC_DIR, name.lower() + ".xml")
            if not os.path.exists(xml_path):
                missing_xml[name] = missing_xml.get(name, 0) + 1
                continue
            npcs.append((z, x, y, name, xml_path))

    if missing_xml:
        print("AVISO - NPCs sem XML (o engine tambem nao os spawnaria):")
        for name, n in sorted(missing_xml.items()):
            print("  %s x%d" % (name, n))

    # ordena por andar, depois y, depois x (estavel p/ o diff)
    npcs.sort(key=lambda e: (e[0], e[1], e[2]))

    lines = []
    lines.append("-- Auto-generated by gen_npcmap.py - do not edit by hand.")
    lines.append("-- Todos os NPCs do mapa (spawn fixo): name, posicao absoluta, outfit.")
    lines.append("NPCMapData = {")
    skipped_no_look = 0
    for z, x, y, name, xml_path in npcs:
        ntree = ET.parse(xml_path)
        nroot = ntree.getroot()
        look = nroot.find("look")
        looktype = int(look.get("type", 0) or 0) if look is not None else 0
        if looktype <= 0:
            skipped_no_look += 1
            continue
        fields = ['name=%s' % _lua_str(name), "x=%d" % x, "y=%d" % y, "z=%d" % z,
                  "looktype=%d" % looktype]
        if look is not None:
            for attr, key in (("head", "head"), ("body", "body"), ("legs", "legs"),
                              ("feet", "feet"), ("addons", "addons")):
                v = int(look.get(attr, 0) or 0)
                if v:
                    fields.append("%s=%d" % (key, v))
        lines.append("  {%s}," % ", ".join(fields))
    lines.append("}")
    lines.append("")
    lines.append("-- Total de NPCs: %d" % (len(npcs) - skipped_no_look))

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    floors = {}
    for z, x, y, name, _ in npcs:
        floors.setdefault(z, 0)
    print("NPCs com XML encontrados: %d (sem look ignorados: %d)"
          % (len(npcs), skipped_no_look))
    print("Escrito em: %s" % OUT_FILE)


def _lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    sys.exit(main())
